### ISSUE TITLE
Patch to update to 0.45

### ISSUE THREAD

**Issue by VorpalBlade** [bartoszek/AUR-ddrescueview#1]
Hi,

I'm not sure how this works with having a separate repository on github for the PKGBUILD instead of using the repo on AUR. Here is a patch to update to the released version 0.4.5 however, attached. I would normally do a PR but I have no idea how this is set up wrt the repo on aur.archlinux.org.

[ddrescueview-0.45.diff.gz](https://github.com/bartoszek/AUR-ddrescueview/files/8899760/ddrescueview-0.45.diff.gz)

**Comment by bartoszek** [comment]
It's simply a mirror, taking advantage of GitHub PR feature that is direly needed in AUR.
You just push a PR here and I'll push it to AUR if it works ¯\\\_(ツ)\_/¯

**Comment by VorpalBlade** [comment]
I have done a PR

**Comment by bartoszek** [comment]
nice
